/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103xx.h"
#include "GPIO.h"
#include "LCD.h"
#include "UART.h"

void Clock_Init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}
int main(void)
{
	uint8_t string[30] = "Learn In Depth   " ;
	USART_Conig_t USART_ConFig ;
	Clock_Init();

	USART_ConFig.BaudRate= USART_BaudRate_9600;
	USART_ConFig.HWFlowCtl=USART_HWFlowCtl_NONE;
	USART_ConFig.IRQ_Enable=USART_IRQ_Enable_NONE;
	USART_ConFig.P_IRQ_CallBack = NULL ;
	USART_ConFig.Parity = USART_Parity_NONE ;
	USART_ConFig.PayLoad_Length=USART_PayLoad_Length8B;
	USART_ConFig.StopBits=USART_StopBits_One ;
	USART_ConFig.USART_MODE=USART_MODE_TX_RX ;

	MCAL_USART_Init(USART1,&USART_ConFig);
	MCAL_USART_GPIO_Set_Pins(USART1);
	while(1)
	{
		MCAL_USART_Send_String(USART1, string, Enable);
		_delay_ms(250) ;
	}
}

