/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103xx.h"
#include "GPIO.h"
#include "EXTI.h"
#include "LCD.h"
#include "Keypad.h"

uint8_t IRQ_Flag = 0 ;

void Clock_Init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}
void EXTI9_CallBack()
{
	IRQ_Flag=1 ;
	LCD_Write_String((uint8_t*)"IRQ EXTI9 Is Happened -\\ ", 0, 0) ;
	_delay_ms(1000);
}
int main(void)
{
	Clock_Init();

	LCD_Init();
	LCD_Clear_Screen();
	EXTI_PinConfig_t EXTI_ConFig ;

	EXTI_ConFig.EXTI_PIN=EXTI9PB9 ;
	EXTI_ConFig.Trigger_Case = EXTI_Trigger_Rising ;
	EXTI_ConFig.P_IRQ_CallBak=EXTI9_CallBack ;
	EXTI_ConFig.IRQ_EN = EXTI_IRQ_Enable ;
	MCAL_EXTI_GPIO_Init(&EXTI_ConFig);
	IRQ_Flag = 1;
	while(1)
	{
		if(IRQ_Flag)
		{
			LCD_Clear_Screen();
			IRQ_Flag = 0 ;
		}
	}

}

