/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103XX.h"
#include "STM32_GPIO.h"

void clock_init()
{
	// Enable clock GPIOA
	RCC_GPIOA_CLK_EN();
	// Enable clock GPIOB
	RCC_GPIOB_CLK_EN();
}
void gpio_init()
{
	GPIO_PinCongif_t Pincfg ;

	Pincfg.GPIO_PinNumber = GPIO_PIN_1 ;
	Pincfg.GPIO_MODE = GPIO_Mode_INPUT_FLO ;
	MCAL_GPIO_INIT(GPIOA, &Pincfg) ;

	Pincfg.GPIO_PinNumber = GPIO_PIN_1 ;
	Pincfg.GPIO_MODE = GPIO_Mode_OUTPUT_PP ;
	Pincfg.GPIO_OutPut_Speed = GPIO_SPEED_10M ;
	MCAL_GPIO_INIT(GPIOB, &Pincfg)	;

	Pincfg.GPIO_PinNumber = GPIO_PIN_13 ;
	Pincfg.GPIO_MODE = GPIO_Mode_INPUT_FLO ;
	MCAL_GPIO_INIT(GPIOA, &Pincfg) ;

	Pincfg.GPIO_PinNumber = GPIO_PIN_13 ;
	Pincfg.GPIO_MODE = GPIO_Mode_OUTPUT_OD ;
	Pincfg.GPIO_OutPut_Speed = GPIO_SPEED_10M ;
	MCAL_GPIO_INIT(GPIOB, &Pincfg)	;
}
void Delay(int  x)
{
		for (int i=0 ; i<x;i++)
			for (int j=0 ; j<255;j++);
}
int main(void)
{
	clock_init();
	gpio_init();

	while(1)
	{
		if (MCAL_GPIO_READ_PIN(GPIOA,GPIO_PIN_1 )==0)
		{
			MCAL_GPIO_TOGGLE_PIN(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_READ_PIN(GPIOA,GPIO_PIN_1 ) == 0);
		}
		if (MCAL_GPIO_READ_PIN(GPIOA,GPIO_PIN_13 ) == 1)
		{
			MCAL_GPIO_TOGGLE_PIN(GPIOB, GPIO_PIN_13);
		}
		Delay(1);
	}
	return 0 ;
}

