/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdio.h"
#include "stdint.h"
typedef volatile uint32_t vuint32_t  ;
#define RCC_BASE						0x40021000
#define GPIOA_BASE 			0x40010800
#define RCC_APB2ENR   							*(vuint32_t *) ( RCC_BASE + 0x18 )
#define GPIOA_CRH       							*(vuint32_t *) ( GPIOA_BASE + 0x04 )
#define GPIOA_CRL       							*(vuint32_t *) ( GPIOA_BASE + 0x00 )
#define GPIOA_ODR      								*(vuint32_t *) ( GPIOA_BASE + 0x0c )
#define EXTI_BASE										0x40010400
#define EXTI_IMR										*(vuint32_t *) ( EXTI_BASE + 0x00 )
#define EXTI_RTSR										*(vuint32_t *) ( EXTI_BASE + 0x08 )
#define EXTI_PR										*(vuint32_t *) ( EXTI_BASE + 0x14 )
#define AFIO_BASE									0X40010000
#define AFIO_EXTICR1							*(vuint32_t *) ( AFIO_BASE + 0x08 )
#define NVIC_EXTIEN0							*(vuint32_t *) ( 0xE000E100 )


void clock_init()
{
	RCC_APB2ENR  |= (1<<2);
	RCC_APB2ENR  |= (1<<0) ;

}
void GPIO_Init ()
{
	GPIOA_CRH     &=  0xFF0FFFFF  ;
	GPIOA_CRH     |=    0x00200000  ;
	GPIOA_CRL |=(1<<2);
}
int main()
{
	clock_init();
	GPIO_Init ();
	AFIO_EXTICR1 = 0;
	//Enable EXTi line 0 (MASK 1)
	EXTI_RTSR |=(1<<0);
	EXTI_IMR |= (1<<0);
	NVIC_EXTIEN0 |= (1<<6);
	while(1);

}
void EXTI0_IRQHandler()
{
	GPIOA_ODR ^= (1<<13);
	EXTI_PR |=(1<<0);
}
